language: php

env:
  - ENCRYPTION_KEY=1234567890qwertyuiopasdfghjklzxc

php:
  - "7.2"

before_script: composer install --no-suggest --no-progress

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse src --no-interaction --no-progress
