#!/usr/bin/env bash

# Reset
Reset="\033[0m"; # Text Reset

# Regular Colors
Black="\033[0;30m"; # Black
Red="\033[0;31m"; # Red
Green="\033[0;32m"; # Green
Yellow="\033[0;33m"; # Yellow
Blue="\033[0;34m"; # Blue
Purple="\033[0;35m"; # Purple
Cyan="\033[0;36m"; # Cyan
White="\033[0;37m"; # White

# Bold
BBlack="\033[1;30m"; # Black
BRed="\033[1;31m"; # Red
BGreen="\033[1;32m"; # Green
BYellow="\033[1;33m"; # Yellow
BBlue="\033[1;34m"; # Blue
BPurple="\033[1;35m"; # Purple
BCyan="\033[1;36m"; # Cyan
BWhite="\033[1;37m"; # White

cmd=${1};
allArgs=${@};
allArgsExceptFirst=${@:2};
secondArg=${2};
valid=false;

if [[ -z "${cmd}" ]]; then
    valid=true;
    printf "${Green}The following commands are available:\n${Yellow}";
    printf "  ./dev up\n";
    printf "  ./dev down\n";
    printf "  ./dev test\n";
    printf "  ./dev psalm [args]\n";
    printf "  ./dev phpstan [args]\n";
    printf "  ./dev phpunit [args]\n"
    printf "  ./dev yarn [args]\n"
    printf "  ./dev cli [args]\n"
    printf "  ./dev composer [args]\n"
    printf "  ./dev login [args]${Reset}\n"
fi

if [[ "${cmd}" = "up" ]]; then
    valid=true;
    docker kill node-buzzingpixel;
    docker-compose -f docker-compose.yml -p buzzingpixel up -d;
    # docker exec -it --user root --workdir /app php-buzzingpixel bash -c "cd /app && composer install";
    composer install;
    docker exec -it --user root --workdir /app node-buzzingpixel bash -c "yarn";
    docker exec -it --user root --workdir /app node-buzzingpixel bash -c "yarn run fab --build-only";

    (cd platform && yarn && cd ..)
fi

if [[ "${cmd}" = "down" ]]; then
    valid=true;
    docker-compose -f docker-compose.yml -p buzzingpixel down;
fi

if [[ "${cmd}" = "phpcs" ]] || [[ "${cmd}" = "test" ]]; then
    valid=true;
    if [[ "${cmd}" = "test" ]]; then
        printf "${Yellow}Running phpcs...${Reset}\n";
    fi
    chmod +x vendor/bin/phpcs
    ./vendor/bin/phpcs config;
    ./vendor/bin/phpcs public;
    ./vendor/bin/phpcs src;
    ./vendor/bin/phpcs tests;
    ./vendor/bin/phpcs phinx.php;
    ./vendor/bin/phpcs cli;
fi

if [[ "${cmd}" = "psalm" ]] || [[ "${cmd}" = "test" ]]; then
    valid=true;
    if [[ "${cmd}" = "test" ]]; then
        printf "\n${Yellow}Running psalm...${Reset}\n";
    fi
    # docker exec -it --user root --workdir /app php-buzzingpixel bash -c "chmod +x /app/vendor/bin/psalm && /app/vendor/bin/psalm ${allArgsExceptFirst}";
    chmod +x vendor/bin/psalm && ./vendor/bin/psalm ${allArgsExceptFirst};
fi

if [[ "${cmd}" = "phpstan" ]] || [[ "${cmd}" = "test" ]]; then
    valid=true;
    if [[ "${cmd}" = "test" ]]; then
        printf "\n${Yellow}Running phpstan...${Reset}\n";
    fi
    # docker exec -it --user root --workdir /app php-buzzingpixel bash -c "chmod +x /app/vendor/bin/phpstan && /app/vendor/bin/phpstan analyse src ${allArgsExceptFirst}";
    chmod +x vendor/bin/phpstan && ./vendor/bin/phpstan analyse src ${allArgsExceptFirst};
fi

if [[ "${cmd}" = "phpunit" ]] || [[ "${cmd}" = "test" ]]; then
    valid=true;
    if [[ "${cmd}" = "test" ]]; then
        printf "\n${Yellow}Running phpunit...${Reset}\n";
    fi
    # docker exec -it --user root --workdir /app php-buzzingpixel bash -c "chmod +x /app/vendor/bin/phpunit && /app/vendor/bin/phpunit --configuration /app/phpunit.xml ${allArgsExceptFirst}";
    chmod +x vendor/bin/phpunit && ./vendor/bin/phpunit --configuration phpunit.xml ${allArgsExceptFirst};
fi

if [[ "${cmd}" = "yarn" ]]; then
    valid=true;
    docker kill node-buzzingpixel;
    docker-compose -f docker-compose.yml -p buzzingpixel up -d;
    docker exec -it --user root --workdir /app node-buzzingpixel bash -c "${allArgs}";
fi

if [[ "${cmd}" = "cli" ]]; then
    valid=true;
    docker exec -it --user root --workdir /app-www php-buzzingpixel bash -c "php ${allArgs}";
fi

if [[ "${cmd}" = "composer" ]]; then
    valid=true;
    docker exec -it --user root --workdir /app php-buzzingpixel bash -c "${allArgs}";
fi

if [[ "${cmd}" = "login" ]]; then
    valid=true;
    docker exec -it --user root ${secondArg}-buzzingpixel bash;
fi

if [[ "${valid}" != "true" ]]; then
    printf "${Red}Specified command not found${Reset}\n";
    exit 1;
fi

exit 0;
