version: '3'

services:
  utility:
    env_file: .env
    image: buzzingpixel/utility:1.1.0
    container_name: utility-buzzingpixel
    environment:
      HOSTNAME: utility-buzzingpixel
    volumes:
      - .:/app
      - cache-volume:/cache-volume
      - db-volume:/db-volume
      - node-modules-volume:/node-modules-volume
      - vendor-volume:/vendor-volume
    command: bash -c "chmod +x /app/scripts/dev/devUtilityScript.sh && /app/scripts/dev/devUtilityScript.sh"
    networks:
      common-buzzingpixel-network:
  web:
    env_file: .env
    image: buzzingpixel/nginx:1.0.2
    container_name: nginx-buzzingpixel
    environment:
      HOSTNAME: nginx-buzzingpixel
    ports:
      - ${HOST_NGINX_PORT}:${DOCKER_NGINX_PORT}
    volumes:
      - ./serverConfig/nginx/${NGINX_CONFIG}.conf:/etc/nginx/conf.d/${NGINX_CONFIG}.conf:delegated
      - .:/app-www:delegated
      - cache-volume:/app-www/cache:delegated
      - vendor-volume:/app-www/vendor:delegated
      - ${SSL_CERT}:/fullchain.pem
      - ${SSL_KEY}:/privkey.pem
    networks:
      common-buzzingpixel-network:
        aliases:
          - buzzingpixel.test
  php:
    env_file: .env
    image: buzzingpixel/php7.2:1.0.6
    container_name: php-buzzingpixel
    environment:
      HOSTNAME: php-buzzingpixel
      COMPOSER_HOME: /composer-home-volume
    volumes:
      - ./serverConfig/php/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini:delegated
      - ./serverConfig/php/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini:delegated
      - ./serverConfig/php/fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
      - .:/app:delegated
      - .:/app-www:delegated
      - cache-volume:/app-www/cache:delegated
      - composer-home-volume:/composer-home-volume:delegated
      - vendor-volume:/app-www/vendor:delegated
    networks:
      common-buzzingpixel-network:
  db:
    env_file: .env
    image: buzzingpixel/mariadb:2.0.1
    container_name: db-buzzingpixel
    restart: always
    environment:
      HOSTNAME: db-buzzingpixel
    user: "1000:50"
    volumes:
      - db-volume:/var/lib/mysql:delegated
    ports:
      - 18974:3306
    networks:
      common-buzzingpixel-network:
  node:
    env_file: .env
    image: node:11.12.0
    container_name: node-buzzingpixel
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/app:delegated
      - node-modules-volume:/app/node_modules
      - yarn-cache-volume:/usr/local/share/.cache/yarn
    command: bash -c "sleep infinity & wait"
    networks:
      common-buzzingpixel-network:

volumes:
  cache-volume:
  composer-home-volume:
  db-volume:
  node-modules-volume:
  vendor-volume:
  yarn-cache-volume:

networks:
  common-buzzingpixel-network:
